# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Ryosuke Onose
email: ryosuke.onose@gmail.com
description: >
  Ryosuke Onose 小野瀬 良佑 # this means to ignore newlines until "url:"

url:  # the base hostname & protocol for your site
baseurl: /~onose # the subpath of your site, e.g. /blog/
last_updated: 2019-08-25_00:42:53

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: onose004
twitter_username: # your Twitter handle
linkedin_username: 良佑-小野瀬-325332100
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username

contact_note: >
  If you cannot reach me via email, please try to find me on Facebook or Instagram

google_analytics: UA-102233158-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Blog
blog_description: Note

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: Blog # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
